### ISSUE TITLE
Will this work with server side rendering

### ISSUE THREAD

**Issue by nodegin** [itaylor/redux-socket.io#16]
Hi, I am new to this package so just a quick question, is this package supports for server side rendering for building universal applications?

**Comment by itaylor** [comment]
Yes, it can definitely work in a server side rendering environment.
How I'd do that is use the redux-socket.io middleware on the client side, but not on the server side. Server-side redux rendering is a bit different, as typically there are no state changes to handle.  The server-side is concerned only with the initial state, so I wouldn't think that it'd be useful to initialize redux-socket.io server side.  

If you're looking at
http://redux.js.org/docs/recipes/ServerRendering.html 
That that'd mean using `applyMiddleware` on redux-socket.io in the `client.js` but not the `server.js`.
