### ISSUE TITLE
bindActionCreators and socket.on('action', ...)

### ISSUE THREAD

**Issue by walkerrandolphsmith** [itaylor/redux-socket.io#7]
When the following is run on the client 

```
store.dispatch({type:'server/hello', data:'Hello!'});
```

The server successfully receives the message.

```
socket.on('action', action => {
    console.log('Got hello data!', action.data);
});
```

All action creators bound to my component using redux's `bindActionCreators` are dispatched on the client, but not received by the server. Am I missing something?

**Comment by itaylor** [comment]
Hmm... Hard to say what could be going wrong there.  `bindActionCreators` doesn't do very much, and it should be calling `dispatch` in the same way as just calling `store.dispatch`.  Are you sure that the events that your action creators return have `type` properties that will be matched by your configuration passed to `createSocketIoMiddleware`?

**Comment by walkerrandolphsmith** [comment]
I didn't make the connection that `createSocketIoMiddleware` configured the prefix to the action type. This solved my problem. This can be closed. 

Thanks!
